### ISSUE TITLE
shell :: 주기적으로 실행 오류

### ISSUE THREAD

**Issue by fver1004** [fver1004/scrapyTest#12]

**Comment by mosmos18** [comment]
/etc/crontab
crontab의 경우 환경변수를 반영하지 않아서 환경변수를 설정하기 위해서는 crontab 내부에 설정을 해주어야 한다.
PATH 설정 후에 scrapy나 hadoop 명령을 오류 없이 이용할 수 있었다.
해결완료 91f9a5545965eceb825ac8b6f46966a4d37b1cdd

**Comment by mosmos18** [comment]
/etc/crontab
crontab의 경우 환경변수를 반영하지 않아서 환경변수를 설정하기 위해서는 crontab 내부에 설정을 해주어야 한다.  
PATH 설정 후에 scrapy나 hadoop 명령을 오류 없이 이용할 수 있었다.
